### ISSUE TITLE
VRF should give the same buff per block

### ISSUE THREAD

**Issue by FriendsFerdinand** [hirosystems/clarity-repl#27]
Assuming the chain tip is at height 11, we retrieve the VRF with the call `get-block-info? vrf-seed u10`.

Every time this is done in the same block, it keep giving a different random value. I think the same VRF should be given every time so as to not have to use a workaround (such as storing the VRF in a variable for the duration of the block). This can give a wrong impression to people testing the VRF functionality and also cause possible bugs when it's time to deploy and remove the workaround.

**Comment by obycode** [comment]
`get_vrf_seed_for_block`, clarity_db.rs:81, currently generates a random number every time the method is called:

```rust
    fn get_vrf_seed_for_block(&self, _bhh: &StacksBlockId) -> Option<VRFSeed> {
        let mut rng = rand::thread_rng();
        let mut buf = [0u8; 32];
        rng.fill_bytes(&mut buf);
        Some(VRFSeed(buf))
    }
```

I'd like to either update this implementation of the database to (a) cache the generated seed, and then check that before generating a new one, or (b) we could generate the seed in a way which is consistent across calls, for example:

```rust
    fn get_vrf_seed_for_block(&self, _bhh: &StacksBlockId) -> Option<VRFSeed> {
        let mut rng: Pcg64 = Seeder::from(_bhh).make_rng();
        let mut buf = [0u8; 32];
        rng.fill_bytes(&mut buf);
        Some(VRFSeed(buf))
    }
```
I found either option won't actually work without modifying the Clarity backing store in several other places because `_bhh` passed into this function is always equal to the `StacksBlockId` of the current tip, not one specific to the height specified in the call. This is because of the implementation of `get_block_at_height` (clarity/database/datastore.rs:69):

```rust
    fn get_block_at_height(&mut self, height: u32) -> Option<StacksBlockId> {
        Some(self.chain_tip)
    }
```

Another option would be to provide consistency by just always returning a VRFSeed of 0, similar to the implementation of the other `HeadersDB` methods here.

@lgalabru, what are your thoughts on this?

**Comment by lgalabru** [comment]
Noted, we should take the constraints from this issue when addressing https://github.com/hirosystems/clarity-repl/issues/18

**Comment by obycode** [comment]
Fixed in latest clarity-repl
