### ISSUE TITLE
Should users build and use the develop branch or the main branch?

### ISSUE THREAD

**Issue by criadoperez** [hirosystems/clarity-repl#71]
If you follow the current instructions of "[Building the CLI from source](https://github.com/hirosystems/clarity-repl#building-the-cli-from-source)" the user will build the *develop* branch instead of the *main* branch.
Is this the desired behavior or should we update the instructions so users build the main branch instead?
If not,  at least we could explain to the users when it is advisable to use one or another?

**Comment by obycode** [comment]
Here are my thoughts.
* If a user is checking out the repository with the intention of building locally, then they are more likely to be comfortable with understanding git branches and could change to `main` if they want a stable release.
* If a user is building locally, it is likely because they intend to make changes to it, in which case, they should be starting with the develop branch, since this is what they will open PRs against.
* Setting `develop` as the default branch is preferable, since that determines against which branch a new PR is opened by default. We don't want to open PRs against `main` except for releases

I think my conclusion is that we should leave `develop` as the default branch, but add a comment in [Building the CLI from source](https://github.com/hirosystems/clarity-repl#building-the-cli-from-source) that lets them know that they need to switch to `main` if they want the code from the last stable release.
